spring:
  jpa:
    #\u5F00\u542FSQL\u8BED\u53E5\u6267\u884C\u65E5\u5FD7\u4FE1\u606F
    show-sql: true
    hibernate:
      #\u914D\u7F6E\u4E3A\u81EA\u52A8\u521B\u5EFA
      ddl-auto: update
  mail:
    # 163\u90AE\u7BB1\u5730\u5740\u4E3Asmtp.163.com\uFF0C\u76F4\u63A5\u586B\u5199
    host: smtp.163.com
    # \u90AE\u7BB1\u8D26\u53F7
    username: huangyilei2001@163.com
    # \u81EA\u52A8\u751F\u6210\u7684\u6388\u6743\u7801
    password: KDOFLEWAHBZVJITE

  datasource:
    url: jdbc:mysql://localhost:3306/db1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: 111.230.48.114

